/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_donneé;

import Application.BDD;
import Application.ResultSetTableModel;
import Application.Parameter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Magic touch
 */
public class Cachier extends javax.swing.JFrame {

    ResultSet rs;
    BDD db;
    int old, dec, now;

    public Cachier() {
        db = new BDD("gestion_de_stock", "amine", "amine", "localhost", 3306);
        db.username = "amine";
        db.password = "amine";
        initComponents();
        table();
        jam();
    }

    public void table() {
        String a[] = {"code_produit", "reference", "desiegnation", "rangemant", "fournisseur", "remise", "prix", "stock"};
        rs = db.querySelectAll("produit");
        table_prod.setModel(new ResultSetTableModel(rs));
    }

    public void importer() {
        String colon[] = {"num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
        rs = db.fcSelectCommand(colon, "vente", "num_facture = '" + txt_fac.getText() + "'");
        table_ven.setModel(new ResultSetTableModel(rs));
    }

    public void jam() {
        Date s = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-YYYY");
        SimpleDateFormat jam = new SimpleDateFormat("HH:MM");
        lbl1.setText(jam.format(s));
        lbl2.setText(tgl.format(s));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        com_recherche = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txt_recherche = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtref = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfou = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtrem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnou = new javax.swing.JTextField();
        txtsto = new javax.swing.JTextField();
        lbltot1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_fac = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_ven = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbltot2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_cas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_pay = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        recherche = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 650));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("  Cachier");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(413, 0, 71, 34);

        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "code_produit", "reference", "desiegnation", "rangemant", "fournisseur", "remise", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 900, 100);

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(lbl1);
        lbl1.setBounds(70, 4, 90, 30);

        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(lbl2);
        lbl2.setBounds(650, 10, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 160);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("recherche par categorie :");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 10, 200, 30);

        com_recherche.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        com_recherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "code_produit", "reference", "desingemant", "rangemant", "fournisseur", "remise", "prix", "stock" }));
        jPanel2.add(com_recherche);
        com_recherche.setBounds(80, 50, 200, 23);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("recherche :");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(30, 80, 100, 25);
        jPanel2.add(txt_recherche);
        txt_recherche.setBounds(140, 80, 180, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("code_produit :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 127, 100, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("reference : ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 160, 80, 20);

        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });
        jPanel2.add(txtcod);
        txtcod.setBounds(140, 120, 160, 30);
        jPanel2.add(txtref);
        txtref.setBounds(140, 150, 160, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("rangemant :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 190, 90, 17);
        jPanel2.add(txtran);
        txtran.setBounds(140, 180, 160, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("fournisseur :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 220, 80, 20);
        jPanel2.add(txtfou);
        txtfou.setBounds(140, 210, 160, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("prix : ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 250, 70, 17);
        jPanel2.add(txtpri);
        txtpri.setBounds(140, 240, 160, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("remise : ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 280, 80, 17);
        jPanel2.add(txtrem);
        txtrem.setBounds(140, 270, 160, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("nouveau prix : ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 310, 100, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("stock sortie : ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 340, 90, 17);
        jPanel2.add(txtnou);
        txtnou.setBounds(140, 300, 160, 30);

        txtsto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstoKeyReleased(evt);
            }
        });
        jPanel2.add(txtsto);
        txtsto.setBounds(140, 330, 160, 30);

        lbltot1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbltot1.setText("0");
        jPanel2.add(lbltot1);
        lbltot1.setBounds(140, 370, 160, 22);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("RP : ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 370, 39, 22);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("ajouter au produit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(60, 400, 200, 31);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 150, 370, 440);

        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("num facteur : ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 10, 80, 17);
        jPanel3.add(txt_fac);
        txt_fac.setBounds(110, 0, 150, 30);

        table_ven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_ven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_venKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table_ven);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 500, 100);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Totale :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 160, 50, 17);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("RP :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(110, 160, 27, 17);

        lbltot2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltot2.setText("0 ");
        jPanel3.add(lbltot2);
        lbltot2.setBounds(180, 160, 90, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Cash : ");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 210, 50, 17);

        txt_cas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_casKeyReleased(evt);
            }
        });
        jPanel3.add(txt_cas);
        txt_cas.setBounds(80, 200, 110, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Payé apres : ");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(200, 210, 79, 17);

        txt_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_payActionPerformed(evt);
            }
        });
        jPanel3.add(txt_pay);
        txt_pay.setBounds(280, 200, 120, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Imprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(140, 260, 200, 31);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("Annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(140, 290, 200, 30);

        recherche.setText("recherche");
        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });
        jPanel3.add(recherche);
        recherche.setBounds(280, 10, 90, 23);

        jButton8.setText("supprimer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(370, 10, 100, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(380, 170, 510, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txt_recherche.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "svp entrer quelque chose");
        } else {
            if (com_recherche.getSelectedItem().equals("code_produit")) {
                rs = db.querySelectAll("produit", "code_produit LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_recherche.getSelectedItem().equals("reference")) {
                rs = db.querySelectAll("produit", "reference LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_recherche.getSelectedItem().equals("desiegnation")) {
                rs = db.querySelectAll("produit", "desiegnation LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_recherche.getSelectedItem().equals("rangemant")) {
                rs = db.querySelectAll("produit", "rangemant LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_recherche.getSelectedItem().equals("fournisseur")) {
                rs = db.querySelectAll("produit", "fournisseur LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_recherche.getSelectedItem().equals("remise")) {
                rs = db.querySelectAll("produit", "remise LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_recherche.getSelectedItem().equals("prix")) {
                rs = db.querySelectAll("produit", "prix LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_recherche.getSelectedItem().equals("stock")) {
                rs = db.querySelectAll("produit", "stock LIKE '%" + txt_recherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        reçue reç = new reçue();
        reç.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtstoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstoKeyReleased
        subtotal();
    }//GEN-LAST:event_txtstoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtcod.getText().equals("") || txtref.getText().equals("")
                || txtran.getText().equals("") || txtfou.getText().equals("")
                || txtrem.getText().equals("") || txtpri.getText().equals("")
                || txtnou.getText().equals("") || txtsto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer vos donneé");
        } else if (txt_fac.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer le numero du facture !!");
        } else {
            String[] colon = {"num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
            String[] isi = {txt_fac.getText(), txtcod.getText(), txtref.getText(),
                txtnou.getText(), txtsto.getText(), lbltot1.getText()};
            System.out.println(db.queryInsert("vente", colon, isi));
            try {
                if (!test_stock()) {
                    JOptionPane.showMessageDialog(this, "le stock est limiter");
                } else {
                    def();
                    table();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println("\n" + ex);
            }
            subtotal();
            importer();
            total();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed
        importer();
        total();
    }//GEN-LAST:event_rechercheActionPerformed


    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        String id = String.valueOf(table_ven.getValueAt(table_ven.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "est ce que tu es  sure que ta veux supprimer",
                "Attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "id=" + id);
        } else {
            return;
        }
        importer();
        total();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txt_casKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_casKeyReleased
        payaprés();
    }//GEN-LAST:event_txt_casKeyReleased

    private void txt_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_payActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        String invoice = txt_fac.getText();
        if (JOptionPane.showConfirmDialog(this, "est ce que tu es sure que tu veux supprimer ", "attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "num_facture" + invoice);
        } else {
            return;
        }
        importer();
        total();


    }//GEN-LAST:event_jButton6ActionPerformed

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked

        txtcod.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 1)));
        txtref.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 2)));
        txtran.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 4)));
        txtfou.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 5)));
        txtpri.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 7)));
        txtrem.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 6)));
        cout();


    }//GEN-LAST:event_table_prodMouseClicked

    private void table_venKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_venKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_table_venKeyReleased

    public void subtotal() {
        double a = Double.parseDouble(txtnou.getText());
        double b = Double.parseDouble(txtsto.getText());
        double c = a * b;
        lbltot1.setText(String.valueOf(c));
    }

    public boolean test_stock() throws SQLException {
        boolean teststock;
        rs = db.querySelectAll("produit", "code_produit='" + txtcod.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txtsto.getText());
        if (old < dec) {
            teststock = false;
        } else {
            teststock = true;
        }
        return teststock;

    }

    public void def() throws SQLException {
        rs = db.querySelectAll("produit", "code_produit ='" + txtcod.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txtsto.getText());
        now = old - dec;
        String nvstock = Integer.toString(now);
        String a = String.valueOf(nvstock);
        String[] colon = {"stock"};
        String[] isi = {a};
        System.out.println(db.queryUpdate("produit", colon, isi, "code_produit='" + txtcod.getText() + "'"));
    }

    public void total() {
        rs = db.executionQuery("SELECT SUM(subtotal) as subtotal FROM vente WHERE num_facture = '" + txt_fac.getText() + "'");
        try {
            rs.next();
            lbltot2.setText(rs.getString("subtotal"));
        } catch (SQLException ex) {
            Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void payaprés() {
        try {
            int a = Integer.parseInt(lbltot2.getText());
            int b = Integer.parseInt(txt_cas.getText());
            int c = b - a;
            txt_pay.setText(Integer.toString(c));
        }catch(Exception e){
            System.err.println(e.getMessage());
        }

    }

    public void cout() {
        double a = Double.parseDouble(txtpri.getText());
        double b = Double.parseDouble(txtrem.getText());
        double c = a - a * (b / 100);
        txtnou.setText(String.valueOf(c));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cachier().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_recherche;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbl1;
    public static javax.swing.JLabel lbl2;
    public static javax.swing.JLabel lbltot1;
    public static javax.swing.JLabel lbltot2;
    private javax.swing.JButton recherche;
    private javax.swing.JTable table_prod;
    private javax.swing.JTable table_ven;
    public static javax.swing.JTextField txt_cas;
    public static transient javax.swing.JTextField txt_fac;
    private javax.swing.JTextField txt_pay;
    private javax.swing.JTextField txt_recherche;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtfou;
    private javax.swing.JTextField txtnou;
    private javax.swing.JTextField txtpri;
    private javax.swing.JTextField txtran;
    private javax.swing.JTextField txtref;
    private javax.swing.JTextField txtrem;
    private javax.swing.JTextField txtsto;
    // End of variables declaration//GEN-END:variables
}
