package base_de_donneé;

import Application.Parameter;
import Application.ResultSetTableModel;
import Application.BDD;
import java.sql.ResultSet;

public class reçue extends javax.swing.JFrame {

    ResultSet rs;
    BDD db;

    public reçue() {
        db = new BDD("gestion_de_stock", "amine", "amine", "localhost", 3306);
        db.username = "amine";
        db.password = "amine";
        initComponents();
        importer();
        date();
    }

    public void importer() {
        String colon[] = {"num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
        rs = db.fcSelectCommand(colon, "vente", "num_facture='" + Cachier.txt_fac.getText() + "'");
        tableImp.setModel(new ResultSetTableModel(rs));
        lbltota1.setText(Cachier.lbltot2.getText());
        lblcash.setText(Cachier.txt_cas.getText());
        payapres();
    }

    public void payapres() {
        int a = Integer.parseInt(Cachier.lbltot2.getText());
        int b = Integer.parseInt(Cachier.txt_cas.getText());
        int c = b - a;
        lblpay.setText(Integer.toString(c));
    }

    public void date() {
        lbld.setText(Cachier.lbl1.getText());
        lblh.setText(Cachier.lbl2.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableImp = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbltota1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblcash = new javax.swing.JLabel();
        lblpay = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();
        lblh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("   reçue");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 0, 130, 42);

        tableImp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableImp);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 590, 100);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 230, 130, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Retour");
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 290, 130, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Total :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 230, 60, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("cache :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 270, 60, 30);

        lbltota1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbltota1.setText("XX");
        jPanel1.add(lbltota1);
        lbltota1.setBounds(350, 237, 110, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Payé apre :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 310, 90, 30);

        lblcash.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblcash.setText("XX");
        jPanel1.add(lblcash);
        lblcash.setBounds(350, 267, 110, 30);

        lblpay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpay.setText("XX");
        jPanel1.add(lblpay);
        lblpay.setBounds(350, 317, 110, 20);

        lbld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(lbld);
        lbld.setBounds(40, 20, 150, 30);
        jPanel1.add(lblh);
        lblh.setBounds(380, 14, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.printComponents(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reçue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reçue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reçue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reçue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reçue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcash;
    private javax.swing.JLabel lbld;
    private javax.swing.JLabel lblh;
    private javax.swing.JLabel lblpay;
    private javax.swing.JLabel lbltota1;
    private javax.swing.JTable tableImp;
    // End of variables declaration//GEN-END:variables
}
