package base_de_donneé;

import Application.BDD;
import Application.ResultSetTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

public class Utilisateur extends javax.swing.JFrame {

    ResultSet rs;
    BDD db;

    public Utilisateur() {
        db = new BDD("gestion_de_stock", "amine", "amine", "localhost", 3306);
        db.username = "amine";
        db.password = "amine";
        initComponents();
        table();
    }

    //fonction pour table_user
    public void table() {
        String a[] = {"id", "id_user", "username", "password", "type"};
        rs = db.querySelectAll("utilisateur");
        table_user.setModel(new ResultSetTableModel(rs));

    }

    public void actualiser() {
        txt_id.setText("");
        txt_us.setText("");
        txt_pa.setText("");
        com_ty.setSelectedItem("typpppe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_pa = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_rech = new javax.swing.JTextField();
        txt_us = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        com_rech = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        com_ty = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Utilisateur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(325, 11, 235, 49);

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "id_user", "username", "password", "type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 78, 772, 100);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 230, 130, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 230, 130, 50);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Recherche");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(300, 390, 150, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setText("Ajouter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 230, 140, 50);

        jButton6.setText("jButton1");
        getContentPane().add(jButton6);
        jButton6.setBounds(90, 230, 110, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Recherch par Catégorie : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 340, 150, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("username :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 360, 70, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("password :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 400, 70, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("type :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 450, 40, 17);

        txt_pa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pa);
        txt_pa.setBounds(100, 400, 140, 30);

        txt_id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(100, 323, 140, 30);

        txt_rech.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechActionPerformed(evt);
            }
        });
        getContentPane().add(txt_rech);
        txt_rech.setBounds(470, 390, 160, 40);

        txt_us.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usActionPerformed(evt);
            }
        });
        getContentPane().add(txt_us);
        txt_us.setBounds(100, 360, 140, 30);

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setText("Actualiser");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(490, 230, 130, 50);

        com_rech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id_user", "username", "password", "type" }));
        getContentPane().add(com_rech);
        com_rech.setBounds(470, 340, 160, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("id_user :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 320, 60, 30);

        com_ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cachier", "directeur" }));
        getContentPane().add(com_ty);
        com_ty.setBounds(100, 440, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (txt_id.getText().equals("") || txt_us.getText().equals("")
                || txt_pa.getText().equals("") || com_ty.getSelectedItem().equals("typpppe")) {
            JOptionPane.showMessageDialog(this, "svp il faut remplir tout les champs !!!");
        } else {
            String[] colon = {"id_user", "username", "password", "type"};
            String[] inf = {txt_id.getText(), txt_us.getText(), txt_pa.getText(), com_ty.getSelectedItem().toString()};
            System.out.println(db.queryInsert("utilisateur", colon, inf));
            table();
            actualiser();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "est ce que tu es sure que tu veux suppremer ", "attention !!!",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("utilisateur", "id = " + id);
        } else {
            return;
        }
        table();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (txt_rech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "svp entrer quelque chose");
        } else {
            if (com_rech.getSelectedItem().equals("id_user")) {
                rs = db.querySelectAll("utilisateur", "id_user LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("username")) {
                rs = db.querySelectAll("utilisateur", "username LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("password")) {
                rs = db.querySelectAll("utilisateur", "password LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("type")) {
                rs = db.querySelectAll("utilisateur", "type LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_paActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechActionPerformed

    private void txt_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        actualiser();
        table();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txt_id.getText().equals("") || txt_us.getText().equals("") || txt_pa.getText().equals("")
                || com_ty.getSelectedItem().equals("typpppe")) {
            JOptionPane.showMessageDialog(this, "svp il faut remplir tout les champs !!!");
        } else {
            String[] colon = {"id_user", "username", "password", "type"};
            String[] inf = {txt_id.getText(), txt_us.getText(), txt_pa.getText(), com_ty.getSelectedItem().toString()};
            String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("utilisateur", colon, inf, "id='" + id + "'"));
            table();
            actualiser();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
        txt_id.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 1)));
        txt_us.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 2)));
        txt_pa.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 3)));
        com_ty.setSelectedItem(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 4)));
    }//GEN-LAST:event_table_userMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rech;
    private javax.swing.JComboBox<String> com_ty;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_user;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_pa;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_us;
    // End of variables declaration//GEN-END:variables
}
